---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - https://github.com/openstack-k8s-operators/gitops/components/argocd/annotations?ref=v0.3.4

resources:
  - ansible-logging-pvc.yaml
  - dataplane-deployment.yaml
  - preprovisioned-nodeset.yaml
