# Install RHOSO using Validated Patterns

Welcome to the Red Hat OpenStack Services on OpenShift (RHOSO) lab instructions.
These instructions will guide you through the installation of the next generation of Red Hat's OpenStack product onto an existing OpenShift Cluster utilizing a bastion host and a single host for the data plane.

In this lab, you will use the following infrastructure:

* A 3 OCP controller/worker 4.16 OCP cluster
* A bastion host to access to the OCP environment
* A RHEL 9.4 virtualised compute host

In this lab, you will cover the following topics:

* xref:install-prereqs.adoc[Perform Prerequisite Operations for the control plane data plane]
* xref:prepare-operator-dependencies.adoc[Prepare RHOSO operator-dependencies with Validated Patterns]
* xref:prepare-openstack-operator.adoc[Prepare RHOSO operators with Validated Patterns]
* xref:prepare-secrets.adoc[Prepare RHOSO secrets with Validated Patterns]
* xref:prepare-networks-gitops.adoc[Prepare the Network using Gitops]
* xref:prepare-controlplane-gitops.adoc[Prepare the Control Plane using Gitops]
* xref:prepare-data-plane-gitops.adoc[Prepare the Data Plane using Gitops]
* xref:deploy-rhoso-using-validatedpatterns.adoc[Deploy RHOSO using Validated Patterns]
* xref:access-gitops.adoc[Access OpenStack]

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

[IMPORTANT]
The content presented in this guide is not officially supported by Red Hat. It is intended solely for exploratory purposes and to gather feedback that may inform potential future productization.

== Fork the Validated Patterns Repository and the lab repository

Fork the following GitHub repositories into your personal GitHub space:

* https://github.com/validatedpatterns-sandbox/rhoso-gitops 
* https://github.com/rhpds/osp-on-ocp-showroom

Make sure you uncheck "Copy the main branch only" checkbox for both repositories.

== Access Your Lab Environment

. Access to the bastion executing the following command: 
+
[source,bash,role=execute,subs=attributes]
----
ssh {bastion_ssh_user_name}@{bastion_public_hostname} -p {bastion_ssh_port} 
----
+
SSH password is `{bastion_ssh_password}`. The uuid of your lab is: `{guid}`
. Optionally copy your public SSH key to the bastion allowing you to authenticate with the server without entering a password every time you connect: 
+
[source,bash,role=execute,subs=attributes]
----
ssh-copy-id -p {bastion_ssh_port} {bastion_ssh_user_name}@{bastion_public_hostname} 
----
+

If needed, you can navigate to the OpenShift console URL: {openshift_cluster_console_url}[{openshift_cluster_console_url}^] using user `admin` and password `{openshift_cluster_admin_password}`

== Add the Bastion SSH Key to the SSH Agent

In the bastion, add the bastion ssh key to the ssh agent:

[source,bash,role=execute,subs=attributes]
----
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/{guid}key.pem
----

If `~/.ssh/config` references a missing `IdentityFile` (for example
`bastion_{guid}`) and `git push` later fails with `Permission denied
(publickey)`, point that entry at the real key:

[source,bash,role=execute,subs=attributes]
----
ln -sf ~/.ssh/{guid}key.pem ~/.ssh/bastion_{guid}
----

== Add the SSH Public Key to GitHub

Copy the public key `~/.ssh/{guid}key.pub` from the bastion to your GitHub account:

1. Copy the SSH public key to your clipboard.
2. Once in your GitHub account page, click on your username in the top right corner and select *Settings*.
3. In the *SSH and GPG keys* section, click *New SSH key*.
4. In the *Title* field, add a descriptive label, such as `"bastion RHOSO gitops key"`.
5. Paste the SSH public key into the *Key* field.
6. Click *Add SSH key*.

== Set Your Repository URL

In the next chapter, we will refer to your forked repository using the variable: "$your_github_id", for example:

[source,bash,subs=attributes]
----
your_github_id=pnavarro
----

== Clone Your Forked Repository

In the bastion, clone your forked repository to the bastion using SSH:

[source,bash]
----
cd
git clone git@github.com:$your_github_id/osp-on-ocp-showroom labrepo
git clone git@github.com:$your_github_id/rhoso-gitops rhoso-gitops
----

*Be sure to review all commands carefully for both functionality and syntax!*
